<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<form id="respond" method="post" action="<?php echo $this->getCommentFormAction() ?>">
	<div class="display-none">
		<input type="hidden" name="comment_post_ID" value="<?php echo $this->getPostId() ?>"/>
		<input type="hidden" name="comment_parent" value="0"/>
	</div>
	<div class="blog_comment">
		
		<?php if ($this->customerMustLogin()): ?>	
			<p><?php echo $this->__('You must be logged in to post a comment.') ?></p>
			<p><button class="button btn-login" type="button" onclick="setLocation('<?php echo $this->getLoginLink() ?>');"><span><span><?php echo $this->__('Login') ?></span></span></button></p>
		<?php else: ?>
			<ul>
				<?php if (!$this->isCustomerLoggedIn()): ?>
					<li><label>Name <span class="required">*</span></label>
  					<input type="text" id="author"  name="author" class="comment_input required-entry" value="<?php echo $this->getSessionData()->getAuthor() ?>">
  					</li>
                                        <li><label>Email  <span class="required">*</span></label>
					  <input type="text" id="email" name="email" class="comment_input required-entry validate-email" value="<?php echo $this->escapeHtml($this->getSessionData()->getEmail()) ?>">
					  </li>
					<!--<li class="fields">
						<div class="field">
							<label for="author" class="required"><?php echo $this->__('Name') ?> <em>*</em></label>
							<div class="input-box">
								<input type="text" id="author" name="author" class="input-text required-entry" value="<?php echo $this->getSessionData()->getAuthor() ?>"/>
							</div>
						</div>
						<div class="field">
							<label for="email" class="required"><?php echo $this->__('Email') ?> <em>*</em></label>
							<div class="input-box">
								<input type="text" id="email" name="email" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getSessionData()->getEmail()) ?>"/>
							</div>
						</div>
					</li>-->
				<?php endif; ?>
				</li>
				   <li class="full_width"><label>Website </label>
				  <input type="text" id="url" name="url" class="comment_input" value="<?php echo $this->escapeHtml($this->getSessionData()->getUrl()) ?>">
				  </li>
				 <li class="full_width"><label>Comment  <span class="required">*</span></label>
				  <textarea id="comment" name="comment" rows="8" cols="45" class="comment_area required-entry"><?php echo $this->escapeHtml($this->getSessionData()->getComment()) ?></textarea>
				  </li>
				<!--<li>
					<label for="url"><?php echo $this->__('Website') ?></label>
					<div class="input-box">
						<input type="text" id="url" name="url" class="input-text" value="<?php echo $this->escapeHtml($this->getSessionData()->getUrl()) ?>"/>
					</div>
				</li>-->
				<!--<li class="wide">
					<label for="comment" class="required"><?php echo $this->__('Comment') ?> <em>*</em></label>
					<div class="input-box">
						<textarea id="comment" name="comment" rows="8" cols="45" class="required-entry"><?php echo $this->escapeHtml($this->getSessionData()->getComment()) ?></textarea>
					</div>
				</li>-->
				<?php if (Mage::helper('wordpress/plugin_commentReplyNotification')->canDisplayOptIn()): ?>
					<li class="control">
						<input type="checkbox" class="checkbox" title="<?php echo $this->__('Receive Reply Notifications') ?>" value="1" id="notifications" name="extra[comment_mail_notify]"<?php if (Mage::helper('wordpress/plugin_commentReplyNotification')->isOptInChecked()): ?> checked="checked"<?php endif; ?>> <label for="notifications"><?php echo $this->__('Notify me of follow-up comments via e-mail') ?></label>
					</li>
				<?php endif; ?>
				<?php if ($this->canDisplayRecaptcha()): ?>
					<?php if ($recaptcha = $this->getRecaptchaHtml()): ?>
						<li id="recaptcha-wrapper" class="wide">
							<?php echo $recaptcha ?>
						</li>
					<?php endif; ?>
				<?php endif; ?>
			
		<?php endif; ?>
	<?php if (!$this->customerMustLogin()): ?>
	<li class="full_width"> 
	  <input type="submit" name="submit" value=" "  class="post_submit" id="post-the-comment"> 
	  </li>	
	<!--<div class="buttons-set">
		<button type="submit" name="submit"  class="button" value="Post your comment" id="post-the-comment">
			<span><span><?php echo $this->__('Post your comment') ?></span></span>
		</button>
	</div>-->
	<script type="text/javascript">
	//<![CDATA[
		var commentForm = new VarienForm('respond');
	//]]>
	</script>
	<?php endif; ?></ul></div>
</form>
