<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<!--<style>
img.aligncenter{float:left !important;width:553px !important;height:313px !important;}
</style>-->
<h4 class="inter-heading">
<img alt="" src="<?php echo $this->getSkinUrl('images/laxunation-text.jpg'); ?>"></h4>
<?php $post = $this->getPost() ?>
<?php
$html = $post->getPostContent();
$doc = new DOMDocument();
$doc->loadHTML($html);
$xpath = new DOMXPath($doc);
$src = $xpath->evaluate("string(//img/@src)");
?>
<?php if ($post): ?>
	<?php $helper = $this->helper('wordpress') ?>
	<?php $author = $post->getAuthor() ?>
	<?php if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
		<?php echo $this->helper('wordpress/plugin_shareThis')->getJavascriptHtml() ?>
	<?php endif; ?>
	<!--<div class="page-title post-title">
		<h1><?php echo $this->escapeHtml($post->getPostTitle()) ?></h1>
	</div>-->
	<div class="post-view">
		<p class="post-date when">
			<?php echo $this->__('Posted on %s', $post->getPostDate()) ?>
		</p>
		<div class="post-entry entry std<?php if ($post->getFeaturedImage): ?> post-entry-with-image<?php endif; ?>">
			<?php if ($post->isViewableForVisitor()): ?>
				<?php if ($featuredImage = $post->getFeaturedImage()): ?>
					<div class="featured-image left"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></div>
				<?php endif; ?>
				<?php if(isset($src) && $src!='') { ?>
				<div class="blog_video"><img style="width:553px;" alt="" src="<?php echo $src; ?>"></div>
				<?php } ?>
				<h6 class="blog_heading"><?php echo $this->escapeHtml($post->getPostTitle()) ?></h6>
				<p style="color: #000000;
    font: 18px/22px Arial,Helvetica,sans-serif;
    padding-bottom: 15px;"><?php echo strip_tags($post->getPostContent()) ?></p>
				<!--<div class="social_icons"><img align="left" alt="" src="<?php echo $this->getSkinUrl('images/blog-social.jpg'); ?>"></div>-->
<div class="social_icons">
<span class='st_facebook_hcount' displayText='Facebook'></span>
<span class='st_twitter_hcount' displayText='Tweet'></span>
<span class='st_googleplus_hcount' displayText='Google +'></span>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "fb1c4bbb-1bf0-445b-9768-20331ae0c919", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
</div>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml() ?>
			<?php endif; ?>
		</div>
		<p>
</p>
		<div class="comment_heading">Comments</div>
		<?php /* if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
				<div class="sharethis-icons" id="sharethis-icons-<?php echo $post->getId() ?>"><?php echo $this->helper('wordpress/plugin_shareThis')->getIcons($post) ?></div>
		<?php endif; */ ?>
		<!--<p class="post-meta details">

			<?php $categories = $post->getParentCategories() ?>
			<?php /* if (count($categories) > 0): ?>
				<span><?php echo $this->__('This entry was posted in') ?> </span>
				<?php $it = count($categories) ?>
				<?php foreach($categories as $category): ?><a href="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a><?php if (--$it > 0): ?>, <?php endif; ?><?php endforeach; ?>
			<?php endif; */ ?>
			<?php $tags = $post->getTags() ?>
			<?php /* if (count($tags) > 0): ?>
				<span><?php echo (count($categories) == 0) ? $this->__('This post was tagged with') : $this->__('and was tagged with') ?> </span> 
				 <?php $it = count($tags) ?>
				 <?php foreach($tags as $tag): ?><a href="<?php echo $tag->getUrl() ?>"><?php echo $tag->getName() ?></a><?php if (--$it > 0): ?>, <?php endif; ?><?php endforeach; ?>
			<?php endif; */ ?>
			<?php //echo $this->__('by') ?> <!--<a href="<?php echo $author->getUrl() ?>"><?php echo $this->escapeHtml($author->getDisplayName()) ?></a
			<?php /*if (false): ?>
				<?php This is hidden by default. Remove the above if (and relevant endif) to display ?>
				<?php if ($post->getCommentCount() == 0): ?>
					<span><?php echo $this->__('There have been %s0 comments%s', '<a href="'.$post->getPermalink().'#respond">', '</a>') ?></span>
				<?php else: ?>
					<span><?php echo $this->__('There have been %s%s comment(s)%s', '<a href="'.$post->getPermalink().'#comments">', $post->getCommentCount(), '</a>') ?></span>
				<?php endif; ?>
			<?php endif; */ ?>
			<?php /* if ($this->canDisplayPreviousNextLinks()): ?>
			<span class="post-skips">
				<?php if (($previous = $post->getPreviousPost()) !== false): ?>
					<a href="<?php echo $previous->getPermalink() ?>" class="post-skip post-skip-previous" title="<?php echo $this->escapeHtml($previous->getPostTitle()) ?>">&larr; <?php echo $this->__('Previous') ?></a>
				<?php endif; ?>
				<?php if (($next = $post->getNextPost()) !== false): ?>
					<a href="<?php echo $next->getPermalink() ?>" class="post-skip post-skip-next" title="<?php echo $this->escapeHtml($next->getPostTitle()) ?>"><?php echo $this->__('Next') ?> &rarr;</a>
				<?php endif; ?>
			</span>
			<?php endif; */ ?>
		</p>-->
		<?php echo $this->getChildHtml('related_posts') ?>
		<?php echo $this->getCommentsHtml() ?>
	</div>
<?php endif; ?>
