<?php /*================================= Easy Auth Default =============================================
<div class="circle" id="circle" style="display:none;">

<a href="#" onclick="$('circle').hide();$('hdw').hide();" class="circle-close"></a>
<div class='item ico-1'> <a href="#" class="icon" onclick="signwith('google')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/Google.png" width="512" height="512" alt="Google" title="Google" /></a> </div>
<div class='item ico-2'>  <a href="#" class="icon" onclick="signwith('facebook')"> <img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/Facebook.png"  alt="Facebook" title="Facebook"/></a></div>
  <div class='item ico-3'> <a href="#" class="icon" onclick="signwith('twitter')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/Twitter.png" alt="Twitter" title="Twitter"/></a></div>
  <div class='item ico-4'> <a href="#" class="icon" onclick="signwith('aol')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/aol.png"  alt="aol" title="aol" /></a></div>
  <div class='item ico-5'> <a href="#" class="icon" onclick="signwith('clavid')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/m0_clavid_sw.png"  alt="clavid" title="clavid"/></a></div>
  <div class='item ico-6'> <a href="#" class="icon" onclick="signwith('livejournal')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/icon_livejournal.png" alt="livejournal" title="livejournal" /></a></div>
  <div class='item ico-7'> <a href="#" class="icon" onclick="signwith('myopenid')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/OpenID.png" alt="OpenID" title="OpenID"/></a></div>
  <div class='item ico-8'> <a href="#" class="icon" onclick="signwith('wordpress')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/wordpress-icon.png"  alt="wordpress" title="wordpress"/></a></div>
  <div class='item ico-9'> <a href="#" class="icon" onclick="signwith('flickr')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/flickr_icon.png" alt="flickr" title="flickr" /></a></div>
  <div class='item ico-10'> <a href="#" class="icon" onclick="signwith('yahoo')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/Yahoo-icon.png" alt="Yahoo" title="Yahoo" /></a></div>
  <div class='item ico-11'> <a href="#" class="icon" onclick="signwith('myspace')"><img src="<?php echo $this->getSkinUrl('css/belvg/')?>img/MySpace.png"  alt="MySpace" title="MySpace"/></a></div>

</div>
<div class="hide-wrapper" id="hdw" style="display:none;"></div>
====================================== END ==============================================================*/ ?>