<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2010-2011 Amasty (http://www.amasty.com)
* @package Amasty_AMCONF
*/
?>

<script type="text/javascript">
LightboxOptions = Object.extend({
    fileLoadingImage:        '<?php echo Mage::getBaseUrl('js') . 'amasty/amconf/images/loading.gif'?>',     
    fileBottomNavCloseImage: '<?php echo Mage::getBaseUrl('js') . 'amasty/amconf/images/closelabel.gif'?>',
    overlayOpacity: 0.6,   // controls transparency of shadow overlay
    animate: true,         // toggles resizing animations
    resizeSpeed: 9,        // controls the speed of the image resizing animations (1=slowest and 10=fastest)
    borderSize: 10,        //if you adjust the padding in the CSS, you will need to update this variable
    // When grouping images this is used to write: Image # of #.
    // Change it for non-english localization
    labelImage: "<?php echo $this->__('Image'); ?>",
    labelOf: "<?php echo $this->__('of'); ?>",
    lBoxEnable: '<?php echo intval(Mage::getStoreConfig('amconf/lightbox/enable'))?>',
    ChangeMainImg:'<?php echo intval(Mage::getStoreConfig('amconf/lightbox/change_main_img'))?>',
    ThumbSize:'<?php echo intval(Mage::getStoreConfig('amconf/size/thumb'))?>',
    MainImgSize:'<?php echo intval(Mage::getStoreConfig('amconf/size/preview'))?>',
    /////////////  Zoom Properties ////////////////////////////////////////////////////////
    zoomImg: '<?php echo Mage::getBaseUrl('js') . 'amasty/amconf/images/mask2.jpg'?>',
    viewerWidth: '<?php echo intval(Mage::getStoreConfig('amconf/zoom/viewer_width'))?>',
    viewerHeight: '<?php echo intval(Mage::getStoreConfig('amconf/zoom/viewer_height'))?>',
    viewerMargin: '<?php echo intval(Mage::getStoreConfig('amconf/zoom/viewer_margin'))?>',
    zoomerActivation: '<?php echo Mage::getStoreConfig('amconf/zoom/zoom_activation')?>',
    viewerPosition: '<?php echo Mage::getStoreConfig('amconf/zoom/position')?>',
    showProductName: '<?php echo intval(Mage::getStoreConfig('amconf/zoom/show_product_name'))?>',
    zoomEnable: '<?php echo intval(Mage::getStoreConfig('amconf/zoom/enable'))?>',
    activeImage: 0,
    images: '',
    flag: 0   // show to zoomer that lbox is working
}, window.LightboxOptions || {});

    function loadAllImages()
    {
        LightboxOptions.images = 
        $$('a[rel^=lightbox]').
        collect(function(anchor){ return [anchor.href, anchor.title]; }).
        uniq();
    } 
    
    document.observe('dom:loaded', function(event){
        LightboxOptions.images = 
        $$('a[rel^=lightbox]').
        collect(function(anchor){ return [anchor.href, anchor.title]; }).
        uniq();
    });

zoomerTpl = new Array();

function passClickToZoomer(div)
{
    $(div).parentNode.select('a').each(function(a){
        a.click();
    });
}
</script>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_thumbSize   = Mage::getStoreConfig('amconf/size/thumb');
    $_previewSize = Mage::getStoreConfig('amconf/size/preview');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>


<?php if (Mage::getStoreConfig('amconf/zoom/enable')): ?>
    <div style="position: relative;">
    <div class="big-image">
    <?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
    <div class="amlabel-div">
          <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
    <?php endif; ?>
    <p class="product-image">
        <?php
            $_img = '
            <a class="wrap" href="' . $this->helper('catalog/image')->init($_product, 'image') . '" rel="zoomer" onclick="return false;">
                <img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_previewSize).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" class="shoe-name" align="middle"/>
                <img id="loadingImg" src="'.Mage::getBaseUrl('js') . 'amasty/amconf/images/Preloader.gif" style="position:absolute; top:0; left:0; display:none;"/>
                <img id="zoomimg" class="zoomIn" src="'.Mage::getBaseUrl('js') . 'amasty/amconf/images/mask2.jpg" style="display:none;"/>
            </a>
            <div id="newdiv" style="position: absolute; z-index: 9999; background-color: #9b9a9a">
                <div id="scroller" style="overflow: hidden; max-width: none;">
                    <img id="oImg" style="display: none; opacity:1; max-width: none;" />
                </div>          
                <div id="divName" style="position: absolute; left: 0px; top: 0px; background-color: black; display:none; color: white; font-weight: bold; text-align: center;">
                </div>
            </div>
            ';
            echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
    <?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
     </div>
    <?php endif; ?>
    <div id="loopdiv" onclick="javascript: passClickToZoomer(this);" style="position: absolute; display: none; z-index: 9999; top: <?php echo $_previewSize - 19 - 5; ?>px; left: <?php echo $_previewSize - 20 - 5; ?>px; display: inline; background-image: url(<?php echo Mage::getBaseUrl('js') . 'amasty/amconf/images/zoom.png'?>); background-repeat: no-repeat; width: 20px; height: 19px;"></div>
    </div>
   </div>
<?php else: ?>
    <?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
          <div class="amlabel-div">
          <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
    <?php endif; ?>
    <p class="product-image product-image-zoom">
        <?php
            $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" class="shoe-name" align="middle" />
            <img id="loadingImg" src="'.Mage::getBaseUrl('js') . 'amasty/amconf/images/loading.gif" style="position:absolute; top:0; left:0; display:none;"/>';
            echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
    <?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
       </div>
    <?php endif; ?>
<?php endif; ?>
    
    <?php if (!Mage::getStoreConfig('amconf/zoom/enable')): ?>
    <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
    <div class="zoom">
        <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
        <div id="track">
            <div id="handle"></div>
        </div>
        <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
    </div>
    <script type="text/javascript">
    //<![CDATA[
        <?php if (!Mage::app()->getRequest()->isAjax()): ?>
        Event.observe(window, 'load', function() {
            product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
        });
        <?php else: ?>
        setTimeout("product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');", 1000);
        <?php endif; ?>
    //]]>
    </script>
    <?php else: ?>
    <?php endif; ?>

<?php else: ?>
    <p class="product-image">
        <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($_previewSize).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
<?php endif; ?>

<script type="text/javascript">
<?php if (Mage::getStoreConfig('amconf/zoom/enable')): ?>
    <?php if (!Mage::app()->getRequest()->isAjax()): ?>
                Event.observe(window, 'load', function(){
    <?php endif; ?>
                $$('a[rel="zoomer"]').each(function (a) {
                   new Zoomer(a);
                });
    <?php if (!Mage::app()->getRequest()->isAjax()): ?>
            });
    <?php endif; ?>
<?php elseif (Mage::getStoreConfig('amconf/lightbox/enable')): ?>
    Event.observe(window, 'load', function () { new Zoomer(); });
<?php endif; ?>
</script>

	



<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="three-thumb">
	<?php foreach ($this->getGalleryImages() as $_image): ?>
        <?php if (Mage::getStoreConfig('amconf/lightbox/enable')): ?>
           <div class="thumb">
                <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" rel="lightbox[<?php echo $_product->getId(); ?>]" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" style="width: 143px; height: 165px;">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(143,165); ?>" width="143" height="165" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                </a>
                <?php /*?><a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" rel="lightbox[<?php echo $_product->getId(); ?>]" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" style="width: <?php echo $_thumbSize; ?>px; height: <?php echo $_thumbSize; ?>px;">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbSize); ?>" width="<?php echo $_thumbSize; ?>" height="<?php echo $_thumbSize; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                </a><?php */?>
            </div>
        <?php else: ?>
            <div class="thumb">
                <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbSize); ?>" width="<?php echo $_thumbSize; ?>" height="<?php echo $_thumbSize; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>	
</div>



<?php endif; ?>
