<?php 
	/**
 * Magento
 * @namespace   Magebuzz
 * @extension   Newsletter Popup (Subscribepopup) 
 * @version     0.1.1
 * @copyright   Copyright (c) 2013 Magebuzz Store. (http://www.magebuzz.com/)
 */

/******* Subscribepopup Templae - head.phtml ******/
?>
<?php 
	$helper = Mage::helper('subscribepopup');
	$timeCookiesTimeout = $helper->timeCookiesTimeout(); 
	$isIncludeJs = $helper->includeJs();
?>
<?php if($helper->isEnabled()): ?>
	<?php if($isIncludeJs):?>
		<script src="<?php echo $this->getJsUrl('magebuzz/subscribepopup/jquery.min.js');?>" type="text/javascript"></script>
		<script src="<?php echo $this->getJsUrl('magebuzz/subscribepopup/jquery.noconflict.js');?>" type="text/javascript"></script>
	<?php endif; ?>
	<script src="<?php echo $this->getJsUrl('magebuzz/subscribepopup/jquery.fancybox.js');?>" type="text/javascript"></script>
	<script src="<?php echo $this->getJsUrl('magebuzz/subscribepopup/jquery.cookie.js');?>" type="text/javascript"></script>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
	var popupCookieExpireAfter = <?php echo $timeCookiesTimeout; ?>;
//]]>
</script>