<?php 
/*
* Copyright (c) 2013 www.magebuzz.com
*/
?>
<?php if ($this->canShowPopup()):?>


	<?php $timeCookiesTimeout = Mage::helper('subscribepopup')->timeCookiesTimeout(); ?>
	<?php $popupDelayTime = Mage::helper('subscribepopup')->popupDelayTime(); ?>
	<?php if(Mage::helper('subscribepopup')->isEnabled()):?>
		<?php if(!isset($_COOKIE['email_subscribed'])):?>
		<?php if ($this->useStaticBlockContent()):?>
		<div id="form-subscribe" class="window">			
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getStaticBlockId())->toHtml(); ?>
		</div>
		<?php else: ?>
			<div id="form-subscribe" class="window">
				<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="subscribe-validate-detail">
					<div class="form-content">
						<label for="newsletter" class="news_header"><?php echo Mage::helper('subscribepopup')->subscribeFormTitle() ?></label>
						<div class="input-box">
							<input type="hidden" value="<?php echo $popupDelayTime;?>">
							<input type="text" name="subscriber_firstname" id="subscriber_firstname" title="firstname" class="input-text required-entry" placeholder="First Name*" >
						</div>
						<div class="input-box">
							<input type="text" name="subscriber_lastname" id="subscriber_lastname" title="lastname" class="input-text required-entry" placeholder="Last Name*" >
						</div>
						<div class="input-box">
							<input type="text" name="email" id="newsletter" title="email address" class="input-text required-entry validate-email" placeholder="Email Address*" >
						</div>
						<div class="input-box">
							<input type="text" name="subscriber_zipcode" id="subscriber_zipcode" title="zipcode" class="input-text required-entry" placeholder="Zip Code*" >
						</div>
						<div style="color: #8F8F8F; font-size: 12px; padding-left: 17px;">*Required Fields</div>
						<div class="actions">
							<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
						</div>
						<?php if(Mage::helper('subscribepopup')->getNotification() != ''):?>
						<!--<div id="notification">
							<address><?php //echo Mage::helper('subscribepopup')->getNotification() ?></address>
						</div>-->
						<div style="width: 168px; height: 30px; margin: 20px auto 0;">
							<!-- AddThis Button BEGIN -->
							<div class="addthis_toolbox addthis_default_style addthis_16x16_style">
							<a class="addthis_button_facebook"></a>
							<a class="addthis_button_twitter"></a>
							<a class="addthis_button_pinterest_share"></a>
							<a class="addthis_button_email"></a>
							<a class="addthis_button_print"></a>
							<a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a>
							</div>
							<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
							<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f0ac6263266f930"></script>
							<!-- AddThis Button END -->
						</div>
						<?php endif; ?>
					</div>
				</form>
				<script type="text/javascript">
				//<![CDATA[
					var newsletterSubscriberFormDetail = new VarienForm('subscribe-validate-detail');
				//]]>
				</script>
			</div>		
		<?php endif;?>
		
		<a id="autostart" href="#form-subscribe"></a>
		<script type="text/javascript">
			if (!jQuery.cookie('afterclose_cookies')) {
				var popupCookieExpireAfter = <?php echo $timeCookiesTimeout ?>;
				<?php if ($popupDelayTime > 0):?>
					jQuery(function() {	
						jQuery("#autostart").fancybox({
							'overlayShow':true,
							frameWidth:838,
							frameHeight:540,
							<?php if (Mage::helper('subscribepopup')->isHideAfterClose()):?>
							afterClose: function() {
								jQuery.cookie('afterclose_cookies', 'true', { expires: popupCookieExpireAfter});
							}
							<?php endif;?>
						});
					});			
					setTimeout( function() {jQuery('#autostart').trigger('click'); }, <?php echo $popupDelayTime*1000;?>);
				<?php else:?>
					jQuery(function() {	
						jQuery("#autostart").fancybox({
							'overlayShow':true,
							frameWidth:838,
							frameHeight:540,
							<?php if (Mage::helper('subscribepopup')->isHideAfterClose()):?>
							afterClose: function() {
								jQuery.cookie('afterclose_cookies', 'true', { expires: popupCookieExpireAfter});
							}
							<?php endif;?>
						}).trigger('click');
					});	
				<?php endif;?>
			}
		</script>
		<?php else: ?>
			<input type="hidden" value="<?php echo $_COOKIE['email_subscribed'];?>">
			<?php 
				$period = $timeCookiesTimeout*86400;
				Mage::getModel('core/cookie')->delete('email_subscribed', $_COOKIE['email_subscribed'], $period);
			?>
		<?php endif; ?>
	<?php endif; ?>	

<?php endif;?>