<?php
	$bannerCollection = $this->getBannerCollection();
	$i = 0;
?>
<?php $timeDelay = $this->getDelayTime() ?>
<?php $showdesc = $this->isShowDescription() ?>
<?php $listStyle = $this->getListStyle() ?>
<?php $imagewidth = $this->getImageWidth() ?>
<?php $imageheight = $this->getImageHeight() ?>
<?php if (count($bannerCollection)): ?>
<div class="cycle-slideshow" id="slde" data-cycle-fx=scrollHorz    data-cycle-timeout=3000    data-cycle-pager="#no-template-pager"    data-cycle-pager-template=""    data-cycle-prev=".prevContro2l"    data-cycle-next=".nextContro2l"> 
	<?php foreach($bannerCollection as $banner): ?>
	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename']?>" title="<?php echo $banner['title']?>" alt="<?php echo $banner['title']?>"/>
	<?php endforeach; ?>
</div>
<div class="con"> <span class="prevContro2l"> </span> <span class="nextContro2l"> </span>
  <div id="no-template-pager" class="cycle-pager external"> 
    <!-- using thumbnail image files would be even better! -->
    <?php foreach($bannerCollection as $banner): ?>
    <div class="thum_img"><img src="<?php echo $this->getUrl()?>image_resizer.php?img=<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $banner['filename'] ?>&newWidth=59&newHeight=52"></div>
    <?php endforeach; ?>       
  </div>
</div>
<?php else:?>
	<?php echo ("Please Upload Banner Or Configuration"); ?>
<?php endif;?>
