
<?php
    $_productCollection = $this->getProductCollection();
    $_helper            = $this->helper('catalog/output');
    $_pageLimit         = $this->getPageLimit();
    $productIds         = array();
?>
<?php if (!$_productCollection->getSize()): ?>
    <?php /* ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php */ ?>
<?php else: ?>
    <div class="new-products">

        <?php $_collectionSize = $_productCollection->getSize() ?>
        <?php $_columnCount = $this->getColumnCount() ?>

        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php $productIds[] = $_product->getId() ?>
            <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid">
            <?php endif ?>
                <li class="item<?php if (($i-1)%$_columnCount==0): ?> first<?php elseif ($i%$_columnCount==0): ?> last<?php endif ?>">

                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php if ($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">
                        <?php if ($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()): ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </li>
            <?php if ($i >= $_pageLimit): ?>
            </ul>
                <?php break ?>
            <?php endif ?>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
            <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php
            // -------- QUICKVIEW script init --------
            $helper     = $this->helper('quickviewpro');
        ?>
        <?php if ($helper->isEnabled() && $productIds): ?>
            <?php
                $settings  = $helper->getSettings();
                $hider     = '';
                if ($settings['overlay_show']) {
                    $hider = 'background-color: ' . $settings['overlay_color'] . ';' .
                             'opacity: ' . $settings['overlay_opacity'] . ';' .
                             'filter:progid:DXImageTransform.Microsoft.Alpha(opacity=' . 100 * $settings['overlay_opacity'] . ');' .
                             '-moz-opacity: ' . $settings['overlay_opacity'] . ';' .
                             '-khtml-opacity: ' . $settings['overlay_opacity'] . ';';
                }
            ?>
            <script type="text/javascript">
                var loader    = new prototypeLoader('<?php echo $this->getSkinUrl('belvg/images/prototype_loader/ajax-loader.gif') ?>');
                var quickviewHomeNew = new Quickview({
                    itemTags       : '.new-products .item',
                    settings       : <?php echo json_encode($settings) ?>,
                    productIds     : <?php echo json_encode($productIds) ?>,
                    ajaxUrl        : '<?php echo Mage::getUrl('quickviewpro/ajax/popup') ?>',
                    cachePrefix    : '<?php echo $helper->getJsCachePrefix() ?>',
                    buttonTemplate : '<a class="quickviewpro-button" rel="{{productId}}" href="javascript:void(0);"><?php echo $this->__('Quickview') ?></a>'
                });

                quickviewHomeNew.init();
            </script>

            <div id="quickviewpro-hider" onclick="quickviewHomeNew.close()" class="quickviewpro-hider" style="display:none;<?php echo $hider ?>"></div>
            <div id="popup" class="quickviewpro-popup" style="display:none;"></div>
        <?php endif; ?>
        <?php //--------------------------------------- ?>
    </div>
<?php endif ?>
